Fixed self hosted adobe not returning extension attributes
bold-commerce/adobe-commerce-bold-checkout pull request #198
Opened 2023-12-21 16:59 UTC by BoldCole

2023-12-21 17:34 UTC, sabelard-bold requested changes
Ensure that we update the payment info on the order properly while we do this. I'm good for everything else.

2023-12-21 17:40 UTC, nicolenorman approved these changes

2023-12-21 19:00 UTC, sabelard-bold approved these changes

2023-12-22 08:14 UTC, nmalevanec approved these changes
Hello @BoldCole,
Could you please make the same changes here? - https://github.com/bold-commerce/adobe-commerce-bold-checkout/blob/e6409813d3fac51de201901b2ea78c1cd4c173f4/Model/Order/PlaceOrder/CreateOrderFromPayload.php#L109

2023-12-22 09:47 UTC, merged